### ISSUE TITLE
Incompatible with Ledger

### ISSUE THREAD

**Issue by Zaquata** [OKTW-Network/FabricProxy-Lite#13]
There appears to be a conflict with the server translations.

**Comment by Tom-The-Geek** [comment]
In the Ledger Discord we've received this crash report that seems to be for this issue, hopefully it's useful for fixing this:
https://cdn.discordapp.com/attachments/910607189448732723/910607487399510046/latest.log

**Comment by cadebarrowes** [comment]
When having this compatibility issue between this and Ledger, for some reason downgrading from Fabric API 0.42.2 to 0.41.3 fixed it.

**Comment by cadebarrowes** [comment]
Has this been resolved? Why was this closed? Using a different Fabric API version certainly won't be a fix that will work in 1.18.

**Comment by james58899** [comment]
@cadebarrowes Yes it was fixed, please wait next version release or you can download latest build from CI.

**Comment by seb303** [comment]
I still have this issue with the latest 1.17.1 FabricProxy-Lite-1.1.5.jar and ledger-1.1.1.jar

Should this fix have been applied to the 1.17.1 builds, or was the fix only for 1.18.x?
